---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  namespace: demo-concourse-flux
  name: helloworld
  labels:
    app: helloworld
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.helloworld: semver:~1.0
spec:
  replicas: 6
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      namespace: demo-concourse-flux
      labels:
        app: helloworld
    spec:
      containers:
      - name: helloworld
        image: osones/demo-concourse-flux:1.0.7
        imagePullPolicy: Always
        ports:
        - name: web
          containerPort: 80
  strategy:
    canary:
      analysis:
        templates:
        - templateName: webcheck
      args:
      - name host
        value: helloworld
      steps:
      - setWeight: 20
      - pause:
          duration: "30s"
      - setWeight: 50
      - pause:
          duration: "30s"
---
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: webcheck
spec:
  args:
  - name: host
  metrics:
  - name: webcheck
    failureLimit: 1
    interval: 5
    successCondition: result == "ok"
    provider:
      web:
        # paceholders are resolved when an AnalysisRun is created
        url: "http://{{args.host}}/"
        jsonPath: "{$.status}" 
---
apiVersion: v1
kind: Service
metadata:
  namespace: demo-concourse-flux
  name: helloworld-svc
spec:
  ports:
  - port: 80
  selector:
    app: helloworld
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  namespace: demo-concourse-flux
  name: helloworld
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: demo-concourse-flux.particule.io
    http:
      paths:
      - backend:
          serviceName: helloworld-svc
          servicePort: 80
